buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.yaml:snakeyaml:2.2'
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.1'
    id 'io.spring.dependency-management' version '1.1.5'
    id 'nu.studer.jooq' version '8.2'
}

group = 'com.portket'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.kafka:spring-kafka'

    testImplementation 'org.springframework.security:spring-security-test'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.11.2'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.2'

    // Swagger dependencies
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Jooq
    implementation 'org.jooq:jooq:3.18.5'
    implementation 'org.springframework.boot:spring-boot-starter-jooq'
    jooqGenerator 'org.postgresql:postgresql'
    runtimeOnly 'org.postgresql:postgresql'

    // Json Serializing
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // .env file support
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'

}

//// application.properties 파일의 경로를 지정합니다.
//def appPropertiesFile = file('src/main/resources/application.yml')
//
//// Properties 객체를 생성하고 파일을 로드합니다.
//def appProperties = new Properties()
//appPropertiesFile.withInputStream { stream ->
//    appProperties.load(stream)
//}

import org.yaml.snakeyaml.Yaml

// application.yml 파일의 경로를 지정합니다.
def appYamlFile = file('src/main/resources/application.yml')

// SnakeYAML을 사용하여 YAML 파일 파싱
def yaml = new Yaml()
def appConfig = yaml.load(appYamlFile.text)


jooq {
    version = '3.18.5'
    configurations {
        main {
            generateSchemaSourceOnCompilation = true
            generationTool {
                jdbc {
                    driver = appConfig.spring.datasource['driver-class-name']
                    url = appConfig.spring.datasource.url
                    user = appConfig.spring.datasource.username
                    password = appConfig.spring.datasource.password
                }
                generator {
                    name = 'org.jooq.codegen.DefaultGenerator'
                    database {
                        name = 'org.jooq.meta.postgres.PostgresDatabase'
                        inputSchema = 'public'
                    }
                    target {
                        packageName = 'com.portket.jooq.generated'
                        directory = 'build/generated/jooq'
                    }
                }
            }
        }
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
